version: '3.7'

services:
  database:
    image: mysql:latest
    container_name: moviepredictor_database
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=predictor
      - MYSQL_USER=predictor
      - MYSQL_PASSWORD=predictor
    networks:
      - database_net
    ports:
      - 3306:3306
    volumes:
      - database_data:/var/lib/mysql
    command: --default_authentication_plugin=mysql_native_password

  adminer:
    image: dehy/adminer:latest
    container_name: moviepredictor_adminer
    networks:
      - database_net
    ports:
      - "8080:80"

networks:
  database_net:
    driver: bridge

volumes:
  database_data:
